FROM python:3.9

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

#copier l'ensemble des fichier du repo 
COPY . .
EXPOSE 8000
#point d'entrée de mon conteneur 
CMD ["python", "manage.py ", "runserver", "0.0.0.0:8080"]